/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect */
        post: operations["inspect_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eval Metrics */
        get: operations["eval_metrics_eval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentOut */
        AgentOut: {
            /**
             * Agent
             * @enum {string}
             */
            agent: "vision" | "analytics" | "knowledge" | "report";
            /** Ok */
            ok: boolean;
            /** Summary */
            summary: string;
            /** Confidence */
            confidence: number;
            /** Needs Human */
            needs_human: boolean;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** Evidence */
        Evidence: {
            /** Source */
            source: string;
            /** Detail */
            detail: string;
            /** Score */
            score: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InspectRequest */
        InspectRequest: {
            /** Question */
            question: string;
            /** Image Path */
            image_path?: string | null;
        };
        /** InspectResponse */
        InspectResponse: {
            /** Answer */
            answer: string;
            /** Ok */
            ok: boolean;
            /** Needs Human */
            needs_human: boolean;
            /** Route */
            route: ("vision" | "analytics" | "knowledge" | "report")[];
            /**
             * Router
             * @enum {string}
             */
            router: "rule" | "llm" | "llm->rule";
            /** Reason */
            reason: string;
            /** Grounding Retriever */
            grounding_retriever: string;
            /** Agents */
            agents: components["schemas"]["AgentOut"][];
            /** Report Markdown */
            report_markdown: string | null;
            /** Latency Ms */
            latency_ms: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    inspect_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eval_metrics_eval_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
